spring:
  application:
    name: admin-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/syzpig/syz-Config.git
server:
  port: 8750 #\u542F\u52A8\u7AEF\u53E3
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
