spring:
  application:
    name: admin-center
server:
  port: 8761 #启动端口


eureka:
  client:
    register-with-eureka: false #false:不作为一个客户端注册到注册中心
    #为true时，可以启动，但报异常：Cannot execute request on any known server
    fetch-registry: false
  server:
    enable-self-preservation: true # 设为false，关闭自我保护
    eviction-interval-timer-in-ms: 60000